### ISSUE TITLE
Question about the convert file

### ISSUE THREAD

**Issue by lambr2** [korhanh/Power-Automate-Workflow-for-Converting-Specific-Files-to-PDF#1]
Hello, thanks for putting this together. I have a question about the file types in your flow. The list of acceptable file formats for OneDrive for business conversion is listed here: 

https://learn.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_get_content_format?view=odsp-graph-online

But the PDF conversion only has:
```doc, docx, epub, eml, htm, html, md, msg, odp, ods, odt, pps, ppsx, ppt, pptx, rtf, tif, tiff, xls, xlsm, xlsx```
as listed file types.

How is it that you are able to convert png and jpg files using the OneDrive for Business connection? I have followed your setup, but I get the following error on the Convert file step:
```
{
  "status": 406,
  "message": "Conversion of this file to PDF is not supported. (InputFormatNotSupported / png)",
  "source": "api.connectorp.svc.ms"
}
```
![image](https://github.com/user-attachments/assets/f54e8919-5ccb-4b44-a184-a84f5e0c9cea)

Did Microsoft remove a bunch of functionality since you wrote this?

Thanks,
Rob

**Comment by korhanh** [comment]
Hi Rob,

Thank you for your feedback! My goal was to convert specific file types supported by OneDrive to PDF. As you mentioned, Microsoft’s documentation indicates that formats like PNG and JPG are not directly supported for PDF conversion.

To address this, I’m planning to develop an "always free" API service that can handle such conversions. This API will support converting formats like PNG and JPG to PDF, alongside other file types. If you can share which file types are a priority for you, I’d be happy to consider adding support for them.

Feel free to reach out if you have any questions or need further assistance!

Thanks,

HKorhan

From: lambr2 ***@***.***>
Sent: Friday, December 13, 2024 2:53 AM
To: korhanh/Power-Automate-Workflow-for-Converting-Specific-Files-to-PDF ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [korhanh/Power-Automate-Workflow-for-Converting-Specific-Files-to-PDF] Question about the convert file (Issue #1)


Hello, thanks for putting this together. I have a question about the file types in your flow. The list of acceptable file formats for OneDrive for business conversion is listed here:

https://learn.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_get_content_format?view=odsp-graph-online

But the PDF conversion only has:
doc, docx, epub, eml, htm, html, md, msg, odp, ods, odt, pps, ppsx, ppt, pptx, rtf, tif, tiff, xls, xlsm, xlsx
as listed file types.

How is it that you are able to convert png and jpg files using the OneDrive for Business connection? I have followed your setup, but I get the following error on the Convert file step:

{

  "status": 406,

  "message": "Conversion of this file to PDF is not supported. (InputFormatNotSupported / png)",

  "source": "api.connectorp.svc.ms"

}

image.png (view on web)<https://github.com/user-attachments/assets/f54e8919-5ccb-4b44-a184-a84f5e0c9cea>

Did Microsoft remove a bunch of functionality since you wrote this?

Thanks,
Rob

**Comment by lambr2** [comment]
Ah okay, that makes sense. Thanks for the prompt reply. My interests in the conversion are on behalf of the organization I work for, and they won't allow the use of 3rd party apps or APIs. I do not think they will let me use your free API.

That being said, your GitHub write ups and instructions are top notch. Thanks again for putting this together.
